config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :modelagem_privacidades
  devise_for :users
  resources :tipo_comunicacoes
  resources :analise_privacidades
  get 'home/index'

    root 'home#index'

end

app/models/analise_privacidade.rb
class AnalisePrivacidade < ActiveRecord::Base
  has_many :tipo_comunicacoes, :dependent => :destroy
  has_many :historico_analises
  has_many :users, :through => :historico_analises
  accepts_nested_attributes_for :tipo_comunicacoes, :reject_if => lambda { |a| a[:tipo_comunicacao].blank? }, :allow_destroy => true
end

app/controllers/analise_privacidades_controller.rb
class AnalisePrivacidadesController < ApplicationController
  before_action :set_analise_privacidade, only: [:show, :edit, :update, :destroy]

  # GET /analise_privacidades
  # GET /analise_privacidades.json
  def index
    @analise_privacidades = AnalisePrivacidade.all
  end

  # GET /analise_privacidades/1
  # GET /analise_privacidades/1.json
  def show
  end

  # GET /analise_privacidades/new
  def new
    
    @analise_privacidade = AnalisePrivacidade.new
    
    #3.times { tipo_comunicacao = @analise_privacidade.tipo_comunicacoes.build }
    
    
  end

  # GET /analise_privacidades/1/edit
  def edit
    
  end

  # POST /analise_privacidades
  # POST /analise_privacidades.json
  def create
    @analise_privacidade = AnalisePrivacidade.new(analise_privacidade_params)
    
    
    
    

    respond_to do |format|
      if @analise_privacidade.save
        format.html { redirect_to @analise_privacidade, notice: 'Analise privacidade was successfully created.' }
        format.json { render :show, status: :created, location: @analise_privacidade }
      else
        format.html { render :new }
        format.json { render json: @analise_privacidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analise_privacidades/1
  # PATCH/PUT /analise_privacidades/1.json
  def update
    respond_to do |format|
      if @analise_privacidade.update(analise_privacidade_params)
        format.html { redirect_to @analise_privacidade, notice: 'Analise privacidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @analise_privacidade }
      else
        format.html { render :edit }
        format.json { render json: @analise_privacidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analise_privacidades/1
  # DELETE /analise_privacidades/1.json
  def destroy
    @analise_privacidade.destroy
    respond_to do |format|
      format.html { redirect_to analise_privacidades_url, notice: 'Analise privacidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analise_privacidade
      @analise_privacidade = AnalisePrivacidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analise_privacidade_params
      #params.require(:analise_privacidade).permit(:rede_social, :url_rede_social, :descricao_analise, tipo_coumunicacoes_attributes: [:id, :tipo_comunicacao, :observacao])
      
      
      params.require(:analise_privacidade).permit!
      
      
      
      
      
    end
end

app/helpers/analise_privacidades_helper.rb
module AnalisePrivacidadesHelper
end

app/views/analise_privacidades/_form.html.erb
<%= form_for(@analise_privacidade) do |f| %>

  <% if @analise_privacidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analise_privacidade.errors.count, "error") %> prohibited this analise_privacidade from being saved:</h2>

      <ul>
      <% @analise_privacidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Rede social' %><br>
    <%= f.text_field :rede_social, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'URL da Rede Social' %><br>
    <%= f.text_field :url_rede_social, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Descrição da análise' %><br>
    <%= f.text_area :descricao_analise, :class=>"form-control" %>
  </div>



  
 <div class="actions">
    <%= f.submit 'Salvar', :class=>"btn btn-primary action"%>
 </div>
  
  
<% end %>

app/views/analise_privacidades/edit.html.erb
<div class="row">
	<div class="col-lg-12">
		<p id="notice"><%= notice %></p>
	
		<h1>Editar Análise de Privacidade</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="card-box">
			<%= render 'form' %>
			
			<%= link_to 'Visualizar', @analise_privacidade %> |
			<%= link_to 'Voltar', analise_privacidades_path %>
		</div>
	</div>
</div>

app/views/analise_privacidades/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<p id="notice"><%= notice %></p>
		
		<%= link_to 'Criar Nova Análise', new_analise_privacidade_path, :class=>"btn-lg btn-primary action link" %>
		
		<h2>Bem vindo(a)<% if user_signed_in? %>, <%= current_user.email %>!</h2><br/>
			<% else %>!</h2><br/>
			<% end %>
	</div>
	
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="card-box">
			
			<h4 class="text-dark  header-title m-t-0">Minhas Análises</h4>
			<p class="text-muted m-b-25 font-13"></p>
			
			<div class="table-responsive">
				<table class="table">
				  <thead>
				    <tr>
				      <th>Rede social</th>
				      <th>URL da rede social</th>
				      <th>Descrição da análise</th>
				      <th class="text-right"></th>
				    </tr>
				  </thead>
				
				  <tbody>
				    <% @analise_privacidades.each do |analise_privacidade| %>
				      <tr>
				        <td><%= analise_privacidade.rede_social %></td>
				        <td><%= analise_privacidade.url_rede_social %></td>
				        <td><%= analise_privacidade.descricao_analise %></td>
				        <td>
				        	<%= link_to 'Visualizar', analise_privacidade, :class=>"text-right" %>
				        	<%= link_to 'Editar', edit_analise_privacidade_path(analise_privacidade), :class=>"text-right" %>
				        	<%= link_to 'Excluir', analise_privacidade, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir essa análise?' }, :class=>"text-right" %></td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="card-box">
			<h4 class="text-dark  header-title m-t-0">Visualização I</h4>
			<p class="text-muted m-b-25 font-13"></p>
		</div>
	</div>	
	<div class="col-lg-6">
		<div class="card-box">
			<h4 class="text-dark  header-title m-t-0">Visualização II</h4>
			<p class="text-muted m-b-25 font-13"></p>
		</div>
	</div>			
</div>

app/views/analise_privacidades/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<p id="notice"><%= notice %></p>
	
		<h1>Criar Nova Análise</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-2 col-md-8">

			<%= render 'form' %>
			
			<%= link_to 'Voltar', analise_privacidades_path %>

	</div>
</div>

app/views/analise_privacidades/show.html.erb
<div class="row">
	<div class="col-lg-12">
		<p id="notice">
			<%= notice %>
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-2 col-md-8">

		<div class="panel panel-info">
			<div class="panel-heading text-center"
			<h4 class="panel-i"><strong><%= @analise_privacidade.rede_social %></strong></h4>
			</div>
			<div class="panel-body">

			<p id="notice"><%= notice %></p>
			<%= link_to 'Novo Tipo Comunicação', new_tipo_comunicacao_path(AnalisePrivacidade.where(:id => params[:format].to_i).pluck(:id).first), :class=>
				"btn-lg btn-primary action link" %>

				<p>
					<strong>URL da rede social:</strong>
					<%= @analise_privacidade.url_rede_social %>
				</p>

				<p>
					<strong>Descrição da análise:</strong>
					<%= @analise_privacidade.descricao_analise %>
				</p>

				<br/>

				<ol>
					<% for comunicacao in @analise_privacidade.tipo_comunicacoes %>

					<li>
						<%= comunicacao.tipo_comunicacao %>
					</li>

					<% end %>
				</ol>

				<%= link_to 'Tipos de Comunicação', tipo_comunicacoes_path(@analise_privacidade.id), :class=>"text-right" %>

				<h3>Tipos de Comunicação</h3>

				<table class="table table-responsive">
					<thead>
						<tr>
							<th>Tipo Comunicacao</th>
							<th>Observação</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>

						<% for tipo_comunicacao in @analise_privacidade.tipo_comunicacoes %>
						
							<tr>
								<td><%= tipo_comunicacao.tipo_comunicacao %></td>
								<td><%= tipo_comunicacao.observacao %> <td><%= link_to 'Visualizar', tipo_comunicacao %></td>
								<td><%= link_to 'Editar', edit_tipo_comunicacao_path(tipo_comunicacao) %></td>
								<td><%= link_to 'Excluir', tipo_comunicacao_path(:id => tipo_comunicacao.id, :analise_privacidade_id => tipo_comunicacao.analise_privacidade.id), method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
								<td>
									
									<div class="row">
									<div class="col-lg-6" >
										<!--colmeia-->
										<div class="panel">
											<P>SEREI A COLMEIA DA VISU</P>
											<div class="panel-body">
												<div id="container-visualizacao-<%= tipo_comunicacao.analise_privacidade.id %>" class="container-grafico"></div>
											</div>
										</div>
									</div>
								</div>
									
								</td>
							</tr>
							
						<% end %>

					</tbody>
				</table>

				<br />

				<%= link_to 'Voltar', analise_privacidades_path(@tipo_comunicacoes), :class => "btn btn-default" %>

			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-2 col-md-4" >
		<div id="options-form" class="actions">
			<%= link_to 'Voltar',  analise_privacidades_path, :class=>"btn btn-default" %>
		</div>
	</div>
	<div class="col-md-4">
		<div id="options-form" class="actions">
			<%= link_to 'Editar', edit_analise_privacidade_path(@analise_privacidade), :class=>"btn btn-primary pull-right" %>
		</div>
	</div>
</div>