config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :modelagem_privacidades
  devise_for :users
  resources :tipo_comunicacoes
  resources :analise_privacidades
  get 'home/index'

    root 'home#index'

end

app/models/modelagem_privacidade.rb
class ModelagemPrivacidade < ActiveRecord::Base
  belongs_to :dimensoes
  belongs_to :controle_privacidades
  belongs_to :tipo_comunicacoes
  has_many :recomendacao_valores
  has_many :valor_dimensoes, :through => :recomendacao_valores
  accepts_nested_attributes_for :tipo_comunicacoes, :dimensoes
end

app/controllers/modelagem_privacidades_controller.rb
class ModelagemPrivacidadesController < ApplicationController
  before_action :set_modelagem_privacidade, only: [:show, :edit, :update, :destroy]

  # GET /modelagem_privacidades
  # GET /modelagem_privacidades.json
  def index
    
    @modelagem_privacidades = ModelagemPrivacidade.all
   # @modelagem_privacidades.dimensoes = @modelo.first
    
    #@modelagem_privacidades = Dimensao.where(:id => params[:id]).all

  end

  # GET /modelagem_privacidades/1
  # GET /modelagem_privacidades/1.json
  def show
  end

  # GET /modelagem_privacidades/new
  def new
    
    
    
    @tipo_comunicacao = TipoComunicacao.where(:id =>  params[:format].to_i)
   
    #@tipo_comunicacao = TipoComunicacao.new
    #@tipo_comunicacao = TipoComunicacao.
    
    8.times { modelagem = @tipo_comunicacao.modelagem_privacidades.build } 
    
    
    #8.times { @modelagem_privacidade = ModelagemPrivacidade.new }  
   
   
    render :text => modelagem
   
    
    
    #@tipo_comunicacoes = TipoComunicacao.where(:analise_privacidade_id =>  params[:format].to_i)
   
   
   
    

  end

  # GET /modelagem_privacidades/1/edit
  def edit
  end

  # POST /modelagem_privacidades
  # POST /modelagem_privacidades.json
  def create
    @modelagem_privacidade = ModelagemPrivacidade.new(modelagem_privacidade_params)

    respond_to do |format|
      if @modelagem_privacidade.save
        format.html { redirect_to @modelagem_privacidade, notice: 'Modelagem privacidade was successfully created.' }
        format.json { render :show, status: :created, location: @modelagem_privacidade }
      else
        format.html { render :new }
        format.json { render json: @modelagem_privacidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modelagem_privacidades/1
  # PATCH/PUT /modelagem_privacidades/1.json
  def update
    respond_to do |format|
      if @modelagem_privacidade.update(modelagem_privacidade_params)
        format.html { redirect_to @modelagem_privacidade, notice: 'Modelagem privacidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @modelagem_privacidade }
      else
        format.html { render :edit }
        format.json { render json: @modelagem_privacidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modelagem_privacidades/1
  # DELETE /modelagem_privacidades/1.json
  def destroy
    @modelagem_privacidade.destroy
    respond_to do |format|
      format.html { redirect_to modelagem_privacidades_url, notice: 'Modelagem privacidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modelagem_privacidade
      @modelagem_privacidade = ModelagemPrivacidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modelagem_privacidade_params
      #params.require(:modelagem_privacidade).permit(:dimensoes, :dimensoes_id, :valor_dimensoes_id, :controle_privacidades_id, :tipo_comunicacoes_id)
       params.require(:modelagem_privacidade).permit!
    end
end

app/helpers/modelagem_privacidades_helper.rb
module ModelagemPrivacidadesHelper
end

app/views/modelagem_privacidades/_form.html.erb
<%= form_for(@modelagem_privacidade) do |f| %>
  <% if @modelagem_privacidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modelagem_privacidade.errors.count, "error") %> prohibited this modelagem_privacidade from being saved:</h2>

      <ul>
      <% @modelagem_privacidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="field">
    <%= f.label :dimensoes_id %><br>
    <%= f.text_field :dimensoes_id, :value => @modelagem_privacidade.inspect %>
  </div>
  
  <div class="field">
    <%= f.label :controle_privacidades_id %><br>
    <%= f.text_field :controle_privacidades_id %>
  </div>
  <div class="field">
    <%= f.label :tipo_comunicacoes_id %><br>
    <%= f.text_field :tipo_comunicacoes_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modelagem_privacidades/edit.html.erb
<h1>Editing Modelagem Privacidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @modelagem_privacidade %> |
<%= link_to 'Back', modelagem_privacidades_path %>

app/views/modelagem_privacidades/index.html.erb
	
	<div class="row">
	<div class="col-lg-6">
		<p id="notice"><%= notice %></p>
		
		<%= link_to 'Nova Modelagem', new_modelagem_privacidade_path, :class=>"btn-lg btn-success action link" %>
		
		<h1>Modelagem de Privacidade</h1>
		
	</div>	
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="card-box">

		<p id="notice"><%= notice %></p>

		<div class="table-responsive">
			
			<table class="table">
			  <thead>
			    <tr>
			      <th>Dimensoes</th>
			      <th>Valor dimensoes</th>
			      <th>Controle privacidades</th>
			      <th>Tipo comunicacoes</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>
			
			  <tbody>
			    <% @modelagem_privacidades.each do |modelagem_privacidade| %>
			      <tr>
			        <td><%= modelagem_privacidade.dimensoes_id %></td>
			        <td><%= modelagem_privacidade.id %></td>
			        <td><%= modelagem_privacidade.controle_privacidades_id %></td>
			        <td><%= modelagem_privacidade.tipo_comunicacoes_id %></td>
			        <td><%= link_to 'Visualizar', modelagem_privacidade %></td>
			        <td><%= link_to 'Editar', edit_modelagem_privacidade_path(modelagem_privacidade) %></td>
			        <td><%= link_to 'Excluir', modelagem_privacidade, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
		
		
	</div>
</div>

app/views/modelagem_privacidades/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<p id="notice">
			<%= notice %>
		</p>

		<h2>Rede Social: </h2>

		Nome da Comunicação:
		<input class="input" />
	</div>
</div>

<div class="col-lg-6">
	<div class="card-box">
		<h4 class="text-dark  header-title m-t-0"></h4>
		<p class="text-muted m-b-25 font-13"></p>
	</div>
</div>
<div class="col-lg-6 card-box">
	
		<h4 class="text-dark  header-title m-t-0">Dimensões</h4>

		<div class="col-lg-6">
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingOne">
						<h4 class="panel-title"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne"> Dimensao #1 </a></h4>
					</div>
					<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
						<div class="panel-body">
							1
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingTwo">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"> Dimensao #2 </a></h4>
					</div>
					<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
						<div class="panel-body">
							2
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> Dimensao #3 </a></h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
						<div class="panel-body">
							3
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour"> Dimensao #4 </a></h4>
					</div>
					<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
						<div class="panel-body">
							4
						</div>
					</div>
				</div>
			</div>
			
			

		</div>

		<div class="col-lg-6">
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingOne">
						<h4 class="panel-title"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="false" aria-controls="collapse5"> Dimensao #5 </a></h4>
					</div>
					<div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading5">
						<div class="panel-body">
							5
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingTwo">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse6" aria-expanded="false" aria-controls="collapse6"> Dimensao #6 </a></h4>
					</div>
					<div id="collapse6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading6">
						<div class="panel-body">
							6	
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse7" aria-expanded="false" aria-controls="collapse7"> Dimensao #7 </a></h4>
					</div>
					<div id="collapse7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading7">
						<div class="panel-body">
							7
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
						<h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse8" aria-expanded="false" aria-controls="collapse8"> Dimensao #8 </a></h4>
					</div>
					<div id="collapse8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading8">
						<div class="panel-body">
							8
						</div>
					</div>
				</div>
			</div>
			
		</div>

	
</div>

<div class="col-lg-6">
	<div class="card-box">
		<h4 class="text-dark  header-title m-t-0">Legenda</h4>
		<p class="text-muted m-b-25 font-13"></p>
	</div>
</div>
<div class="col-lg-6 card-box">
	
		<h4 class="text-dark  header-title m-t-0">Mapa</h4>
		<p class="text-muted m-b-25 font-13"></p>
</div>

<% if true %>
<%= render 'form' %>
<% end %>

<%= link_to 'Back', modelagem_privacidades_path %>

app/views/modelagem_privacidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dimensoes:</strong>
  <%= @modelagem_privacidade.dimensoes %>
</p>

<p>
  <strong>Valor dimensoes:</strong>
  <%= @modelagem_privacidade.valor_dimensoes %>
</p>

<p>
  <strong>Controle privacidades:</strong>
  <%= @modelagem_privacidade.controle_privacidades %>
</p>

<p>
  <strong>Tipo comunicacoes:</strong>
  <%= @modelagem_privacidade.tipo_comunicacoes %>
</p>

<%= link_to 'Edit', edit_modelagem_privacidade_path(@modelagem_privacidade) %> |
<%= link_to 'Back', modelagem_privacidades_path %>