config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :modelagem_privacidades
  devise_for :users
  resources :tipo_comunicacoes
  resources :analise_privacidades
  get 'home/index'

    root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/analise_privacidade.rb
class AnalisePrivacidade < ActiveRecord::Base
  has_many :tipo_comunicacoes, :dependent => :destroy
  has_many :historico_analises
  has_many :users, :through => :historico_analises
  accepts_nested_attributes_for :tipo_comunicacoes, :reject_if => lambda { |a| a[:tipo_comunicacao].blank? }, :allow_destroy => true
end

app/models/categoria_dimensao.rb
class CategoriaDimensao < ActiveRecord::Base
  has_many :dimensoes
end

app/models/controle_privacidade.rb
class ControlePrivacidade < ActiveRecord::Base
  has_many :modelagem_privacidades
end

app/models/dimensao.rb
class Dimensao < ActiveRecord::Base
  belongs_to :categoria_dimensoes
  has_many :valor_dimensoes
  has_many :modelagem_privacidades
end

app/models/historico_analise.rb
class HistoricoAnalise < ActiveRecord::Base
  belongs_to :user
  belongs_to :analise_privacidade
end

app/models/modelagem_privacidade.rb
class ModelagemPrivacidade < ActiveRecord::Base
  belongs_to :dimensoes
  belongs_to :controle_privacidades
  belongs_to :tipo_comunicacoes
  has_many :recomendacao_valores
  has_many :valor_dimensoes, :through => :recomendacao_valores
  accepts_nested_attributes_for :tipo_comunicacoes, :dimensoes
end

app/models/nivel_privacidade.rb
class NivelPrivacidade < ActiveRecord::Base
  has_many :dimensoes
end

app/models/recomendacao_valor.rb
class RecomendacaoValor < ActiveRecord::Base
  belongs_to :modelagem_privacidades
  belongs_to :valor_dimensoes
end

app/models/tipo_comunicacao.rb
class TipoComunicacao < ActiveRecord::Base
  belongs_to :analise_privacidade
  has_many :modelagem_privacidades
  accepts_nested_attributes_for :modelagem_privacidades
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  has_many :historico_analises
  has_many :analise_privacidades, :through => :historico_analises
end

app/models/valor_dimensao.rb
class ValorDimensao < ActiveRecord::Base
  belongs_to :dimensao
  belongs_to :nivel_privacidade
  has_many :modelagem_privacidades
  has_many :modelagem_privacidades, :through => :recomendacao_valores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tipo_comunicacoes_controller.rb
class TipoComunicacoesController < ApplicationController
  before_action :set_tipo_comunicacao, only: [:show, :edit, :update, :destroy]

  # GET /tipo_comunicacoes
  # GET /tipo_comunicacoes.json
  def index 
    
    
    @tipo_comunicacoes = TipoComunicacao.new
    
    @tipo_comunicacoes = TipoComunicacao.where(:analise_privacidade_id =>  params[:format].to_i) 
    
    
    #render :text =>  @tipo_comunicacoes.size()
    
       
  end

  # GET /tipo_comunicacoes/1
  # GET /tipo_comunicacoes/1.json
  def show
  end

  # GET /tipo_comunicacoes/new
  def new
    
    @tipo_comunicacao = TipoComunicacao.new
    @tipo_comunicacao.build_analise_privacidade
    
    @tipo_comunicacao.build_analise_privacidade(:id => params[:format].to_i)
  
  
    8.times { @tipo_comunicacao.modelagem_privacidades.build }
    
    #render :text => params
    
  end

  # GET /tipo_comunicacoes/1/edit
  def edit
   
  end

  # POST /tipo_comunicacoes
  # POST /tipo_comunicacoes.json
  def create
    @tipo_comunicacao = TipoComunicacao.new(tipo_comunicacao_params)

    respond_to do |format|
      if @tipo_comunicacao.save
        format.html { redirect_to @tipo_comunicacao, notice: 'Tipo comunicacao was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_comunicacao }
      else
        format.html { render :new }
        format.json { render json: @tipo_comunicacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_comunicacoes/1
  # PATCH/PUT /tipo_comunicacoes/1.json
  def update
    respond_to do |format|
      if @tipo_comunicacao.update(tipo_comunicacao_params)
        format.html { redirect_to @tipo_comunicacao, notice: 'Tipo comunicacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_comunicacao }
      else
        format.html { render :edit }
        format.json { render json: @tipo_comunicacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_comunicacoes/1
  # DELETE /tipo_comunicacoes/1.json
  def destroy
    
    @analise_privacidade = @tipo_comunicacao.analise_privacidade_id
    
    #render :text => @privacidadetipo_comunicacoes_url
    
    @tipo_comunicacao.destroy
    respond_to do |format|
      format.html { redirect_to tipo_comunicacoes_path(@analise_privacidade), notice: 'Tipo comunicacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_comunicacao
      @tipo_comunicacao = TipoComunicacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_comunicacao_params
        #params.require(:tipo_comunicacao).permit(:analise_privacidade_attributes, :rede_social, :analise_privacidades_id, :tipo_comunicacao, :observacao)
         params.require(:tipo_comunicacao).permit!
    end
end

app/helpers/analise_privacidades_helper.rb
module AnalisePrivacidadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modelagem_privacidades_helper.rb
module ModelagemPrivacidadesHelper
end

app/helpers/tipo_comunicacoes_helper.rb
module TipoComunicacoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>PryVis</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">
			<div>
				<p class="notice">
					<%= notice %>
				</p>
				<p class="alert">
					<%= alert %>
				</p>

				<p class="navbar-text pull-right"></p>

				<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<%= link_to "PryVis", home_index_path, :class=>"navbar-brand" %>
							
					</div>
					<!-- Top Menu Items -->
					<ul class="nav navbar-right top-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="glyphicon glyphicon-file"></i> Tutorial</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-user"></i> <% if user_signed_in? %>
							<%= current_user.email %>
							<% else %>
							User access
							<% end %> <b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<% if user_signed_in? %>
								<li>
									<%= link_to " Edit profile", edit_user_registration_path, :class => 'glyphicon glyphicon-cog' %>
								</li>
								<li class="divider"></li>
								<li>
									<%= link_to " Logout", destroy_user_session_path, method: :delete, :class => 'glyphicon glyphicon-log-out' %>
								</li>
								<% else %>
								<li>
									<%= link_to "Sign up", new_user_registration_path %>
								</li>
								<li>
									<%= link_to " Login", new_user_session_path, :class => 'glyphicon glyphicon-log-in' %>
								</li>
								<% end %>
							</ul>
						</li>
					</ul>
				</nav>
				<div id="page-wrapper">
					<div class="container">
						<%= yield %>
					</div>
					<!-- /.container-fluid -->
				</div>
				<!-- /#page-wrapper -->
			</div>
			<!-- /#wrapper -->
	</body>
</html>